### ISSUE TITLE
Faster way to include random effect in the model

### ISSUE THREAD

**Issue by xwz-123** [neural-structured-additive-learning/deepregression#12]
Dear all,

I'd like to fit a mixed model with `deepregression` and model the random effect of `X` with `s(X, bs = 're')`. My problem is that the levels of the grouping variables is really high** and it takes really very long time to fit the smoother***. 

Is there a method to solve this problem? Thanks a lot in advance for any help.

_** There're 7366 observations, but 4950 different different groups. Quite often, one specific group has only one observation.
*** It takes such a long time that I terminate the execution manually. So I don't know how long does the fitting of smoother really take._

**Comment by davidruegamer** [comment]
Hi,

Thanks for your interest. There is indeed an add-on package for this we are currently developing, motivated by [a recent publication with a similar problem](https://arxiv.org/abs/2205.13080). I just open-sourced it [here](https://github.com/neural-structured-additive-learning/safareg). It's not well-tested yet and there might still be bugs in it, but you should able to do something like this:

```R
path_to_deepregression <- "XXXXXXXXXXXX"
path_to_safareg <- "YYYYYYYYYYY"

### Load packages
devtools::load_all(file.path(path_to_deepregression, "deepregression"))
# load safareg for additional processor
devtools::load_all(file.path(path_to_safareg, "safareg"))

### Simulate data
n <- 7366
p_group <- 4950

data <- data.frame(y = rnorm(n), x = rnorm(n), 
                   # make every group present at least once
                   groups = c(1:p_group, 
                              sample(1:p_group, n-p_group, replace = TRUE)
                              )
)

### Define degrees-of-freedom for the random effect
my_df <- 10
# using https://arxiv.org/pdf/2110.03513.pdf, Section A.3.1,
# the corresponding lambda is given by the solution of
df2l <- function(lambda){
  n_k <- c(table(data$groups))
  sum((n_k*(n_k+2*lambda))/(n_k+lambda)^2) - my_df
}

(my_lambda <- uniroot(df2l, c(0, 1e+16), 
                      tol = sqrt(.Machine$double.eps))$root
)

### Define the factor variable in the formula with the fac function
mean_form <- as.formula(paste0("~ x + fac(groups, lambda = ", my_lambda, ")"))

mod <- deepregression(y = data$y,
                      data = data,
                      list_of_formulas = list(
                        loc = mean_form,
                        scale = ~ 1
                      ),
                      additional_processors = list(
                        # supply the new processor here:
                        fac = fac_processor
                      ))

# should take < 10sec
mod %>% fit(epochs = 10L)
```

This should provide you with the exact random effect prediction of the feature `groups` (modulo some shrinkage induced by the early stopping). The only thing that is still required to do manually derive the degrees-of-freedom for the random effect. In the code above there is a way to map the degrees-of-freedom to a $\lambda$ value.

**Comment by xwz-123** [comment]
Thanks a lot for your reply! I still have the following question/problem:

1. Could you please elaborate more on how to calculate the degrees of freedom? I've read the A.2 and A.3.1 part of the paper, but still can't get how to derive the df.

2. When I run 
```R
mod <- deepregression(y = data$y,
                      data = data,
                      list_of_formulas = list(
                        loc = mean_form,
                        scale = ~ 1
                      ),
                      additional_processors = list(
                        # supply the new processor here:
                        fac = fac_processor
                      ))
```
I get the following error message:
```R
Error in extractlen(term, data) : could not find function "extractlen"
```
Perhaps I haven't properly loaded the package `safareg`?

**Comment by davidruegamer** [comment]
Thx for your reply. 

- About the error message: I just forgot to export some functions. Can you try again?
- About the degrees-of-freedom: This concept is similar or almost the same as, e.g., used in [`mboost`](https://cran.r-project.org/web/packages/mboost/index.html). The details are explained in our [paper](https://arxiv.org/pdf/2104.02705.pdf) page 15, paragraph *Smoothness penalties*. In short: Both splines and random effects can be represented as penalized linear effects with a penalty parameter $\lambda$ and a penalty matrix (determined by the type of spline or random effect). While `mgcv` determines the different $\lambda$ values (= the smoothness of every functions) automatically, `deepregression` still requires the user to specify a flexibility amount. As absolute $\lambda$ values have no meaningful interpretation, the user can define the flexibility in `deepregression` instead via the degrees-of-freedom (df). For splines, df = 1, for example, means you are estimating a linear function. The more df, the more wiggly the spline will be. In many cases, the maximum df for a spline is its amount of basis functions. In practice, fixing one overall df value for all splines turned out to work very well in `deepregression`. 

Since random effects can be interpreted as linear effects with a Ridge regularization, this idea works also for random effects. For your random effect use case, df = 10 would, e.g., imply that you penalize the variation of the 4950 groups to an amount as if there would only be 10 groups. In particular, any df value smaller 4950 implies shrinkage towards zero (the smaller the df, the more shrinkage). You can also interpret the df as some form of random effect variance. The smaller the df, the smaller the random effect variance will be.

Especially for random effects I must admit that a user-specified value is not ideal. We will soon add functionality to `deepregression` to also automatically estimate the $\lambda$ s (and therefore the random effect variance(s)). For now what you could do is to cross-validate or tune the df value. Since the conversion from $\lambda$ to df is not implemented in `safareg` yet, I provided the function `df2l` and how to calculate `lambda` given `df` in my first reply. You would just need to try out different df values, calculate the corresponding `lambda` value, run `deepregression` and check the goodness-of-fit criterion of your choice. 

Let me know if that helps.

**Comment by xwz-123** [comment]
Thanks a lot for your explanation, it really helps me a lot.

I get the error

```R
Error in data[[extractvar(term)]] : subscript out of bounds
```

When I try to run the following codes for my data:

```R
mod <- deepregression(
  y = data$y,
  data = data,
  family = 'bernoulli_prob',
  list_of_formulas = list(prob = ~ 1 + x + fac(group, lambda = my_lambda)),
  additional_processors = list(fac = fac_processor)
)
```

where

```R
> class(data)
[1] "data.table" "data.frame"

> class(data$y)
[1] "numeric"

> class(data$x)
[1] "numeric"
```

Do you perhaps why I get the error message?

**Comment by davidruegamer** [comment]
Is the factor variable in your case called `group` or `groups`?
Another cause could be that internally, `deepregression` cannot access `my_lambda`, so you would have to provide the formula as follows: 
```
...R
    list_of_formulas = list(prob = as.formula(paste0("~ x + fac(group, lambda = ", my_lambda, ")"))),
...
```

Let me know if that solves the problem.

**Comment by xwz-123** [comment]
The problem is solved. Thanks again for your help!

**Comment by xwz-123** [comment]
Hi, David,

I'm sorry to reopen the issue but I'd like to ask whether it is possible to quantify the estimated random effect.

Take your simulation as an example, when I call 
```R
str(cf <- mod %>% coef(), 1)
```
I will get
```R
List of 3
 $ x                                     : num [1, 1] -0.00186
 $ fac(groups, lambda = 1470.47937434199): num[0 , 1] 
 $ (Intercept)                           : num [1, 1] 0.0059
```

So I can't get estimated random effect for `groups`? Something like `ranef` in `lme4`?

**Comment by davidruegamer** [comment]
Hmm ok. That's odd. For me the list of coefficients looks like this:

```R
> str(cf <- mod %>% coef(),1)
List of 3
 $ x                                     : num [1, 1] 0.021
 $ fac(groups, lambda = 1470.47409223489): num [1:4950, 1] -0.1166 -0.1121 -0.1698 -0.1636 -0.0193 ...
 $ (Intercept)                           : num [1, 1] 0.00182
 ```
Have you changed the code above in any way? Could you also please post your `sessionInfo()`? I guess this will be some version issue, but not sure.

But yes, there is an alternative way to access the estimated coefficients. You can always print the model's weights like this:

```R
mod$model$weights
```

which should give you something like this

```R
[[1]]
<tf.Variable 'x_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.02099758]], dtype=float32)>

[[2]]
<tf.Variable 'fac_groups_lambda_1470_47409223489__1/kernel:0' shape=(4950, 1) dtype=float32, numpy=
array([[-0.11655852],
       [-0.11206187],
       [-0.16977598],
       ...,
       [ 0.10897723],
       [ 0.09219299],
       [-0.13159196]], dtype=float32)>

[[3]]
<tf.Variable '1_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.00182277]], dtype=float32)>

[[4]]
<tf.Variable '1_2/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.07432961]], dtype=float32)>
```

Then subset to the layer of your interest (here the second one) and convert it to a matrix object:

```R
> str(cf <- as.matrix(mod$model$weights[[2]]), 1)
 num [1:4950, 1] -0.1166 -0.1121 -0.1698 -0.1636 -0.0193 ...
```

**Comment by xwz-123** [comment]
Thanks for your reply. I use the codes you've provided previously except I install `deepregression` and `safareg` with following codes:

```R
devtools::install_github("neural-structured-additive-learning/deepregression")
devtools::install_github("neural-structured-additive-learning/safareg")
```

And then load the package with 

```R
library(deepregression)
library(safareg)
```

I've tried to use

```R
mod$model$weights
```
to get estimated random effect, but I still can't anything:

```R
> mod$model$weights
[[1]]
<tf.Variable 'x_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.0018618]], dtype=float32)>

[[2]]
<tf.Variable 'fac_groups_lambda_1470_47937434199__1/kernel:0' shape=(0, 1) dtype=float32, numpy=array([], shape=(0, 1), dtype=float32)>

[[3]]
<tf.Variable '1_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.00589747]], dtype=float32)>

[[4]]
<tf.Variable '1_2/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.00257472]], dtype=float32)>
```

Here is the result for `sessionInfo()`:

```R
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] safareg_0.1        deepregression_0.2

loaded via a namespace (and not attached):
 [1] reticulate_1.25      tidyselect_1.1.2     remotes_2.4.2       
 [4] purrr_0.3.4          splines_4.2.1        lattice_0.20-45     
 [7] vctrs_0.4.1          generics_0.1.3       testthat_3.1.4      
[10] usethis_2.1.6        mgcv_1.8-40          base64enc_0.1-3     
[13] utf8_1.2.2           rlang_1.0.4          pkgbuild_1.3.1      
[16] pillar_1.8.1         glue_1.6.2           withr_2.5.0         
[19] DBI_1.1.2            sessioninfo_1.2.2    lifecycle_1.0.1     
[22] tensorflow_2.9.0     devtools_2.4.3       memoise_2.0.1       
[25] callr_3.7.0          fastmap_1.1.0        tfruns_1.5.0        
[28] ps_1.7.1             curl_4.3.2           fansi_1.0.3         
[31] Rcpp_1.0.9           cachem_1.0.6         desc_1.4.1          
[34] pkgload_1.2.4        jsonlite_1.8.0       fs_1.5.2            
[37] brio_1.1.3           png_0.1-7            processx_3.7.0      
[40] dplyr_1.0.9          grid_4.2.1           rprojroot_2.0.3     
[43] here_1.0.1           tfprobability_0.15.0 cli_3.3.0           
[46] tools_4.2.1          keras_2.9.0          magrittr_2.0.3      
[49] tibble_3.1.8         crayon_1.5.1         whisker_0.4         
[52] pkgconfig_2.0.3      zeallot_0.1.0        ellipsis_0.3.2      
[55] Matrix_1.4-1         prettyunits_1.1.1    assertthat_0.2.1    
[58] rstudioapi_0.14      R6_2.5.1             nlme_3.1-157        
[61] compiler_4.2.1
```

**Comment by davidruegamer** [comment]
Seems like this was both my sloppy way to setup the example and not writing code robust enough... 

It's very likely that your problem was caused due to `data$groups` not being a factor variable. So it should work if you setup the data as follows:

```R
data <- data.frame(y = rnorm(n), x = rnorm(n), 
                   # make every group present at least once
                   groups = factor(c(1:p_group, 
                              sample(1:p_group, n-p_group, replace = TRUE)
                              ))
)
```

or by installing `safareg` again which now [enforces](https://github.com/neural-structured-additive-learning/safareg/blob/main/R/layers.R#L927) a factor variable when checking the number of levels. 

Let me know if that solves your problem.

**Comment by xwz-123** [comment]
Yes, the problem is solved. Thanks a lot!

**Comment by davidruegamer** [comment]
Great! Thanks for bringing this up.
