### ISSUE TITLE
 installation of deepregression  package                                               

### ISSUE THREAD

**Issue by wxhmath** [neural-structured-additive-learning/deepregression#8]
When I installed deepregression package, an error occurred, how should I solve it.Please give me some advice,thanks.

keras::install_keras()
 Error installing package(s): "\"tensorflow==2.8.*\"", "\"tensorflow-hub\"", "\"scipy\"", "\"requests\"", "\"Pillow\"", "\"h5py\"", "\"pandas\""
 Warning message:
In shell(fi) :
  'C:\Users\ADMINI~1\AppData\Local\Temp\RtmpkJFdQ4\file15881d5d4101.bat'

**Comment by davidruegamer** [comment]
Hi,

Could you please provide the complete output of the error message? Otherwise there is no way to tell what the actual problem is (e.g., by using `traceback(max.lines = 10)` after the error occurred). Also, could you provide the output of `reticulate::py_config()`? 
Does `library(tensorflow)` and `library(keras)` work for you?

Best,
David

**Comment by wxhmath** [comment]
I set the environment path for miniconda. It looks that it works already.

Thank you very much for your help.

**Comment by davidruegamer** [comment]
Great! Many thanks for letting us know. I have added a troubleshooting section in the Readme to explain your approach (?) in a bit more detail.
